
name = "jimikki-app"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "jimikki-db"
database_id = "your-database-id"

[vars]
GOOGLE_SERVICE_EMAIL = "jimikki-bot@jimikki.iam.gserviceaccount.com"
GOOGLE_DRIVE_FOLDER_ID = "11f4fPII1txdbWrAunB3vtvfbxHiK7L75"
